# -*- coding: utf-8 -*-
"""01-python_variables.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wRpOOVoKaF6XUTAEL3eqFxkmsGtG0CSb
"""

# 1. Basic Variable - Name

name = "Akshata"
print("name:", name)


# 2. Basic Variable - Age

age = 22
print("age:", age)


# 3. Basic Variable - Marks

marks = 98
print("marks:", marks)


# 4. Multiple Variables

name = "Akshata"
age = 22
city = "Jath"
course = "Python"

print("Name:", name)
print("Age:", age)
print("City:", city)
print("Course:", course)


# 5. Variables with Different Data Types

name = "Akshata"
age = 22
marks = 89.6
is_student = True

print(type(name))
print(type(age))
print(type(marks))
print(type(is_student))


# 6. Swap Two Variables

a = 10
b = 20

a, b = b, a

print("a:", a)
print("b:", b)


# 7. Arithmetic Operations Using Variables

a = 30
b = 23

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)


# 8. Calculate Area of Rectangle

length = 10
width = 5

area = length * width

print("Area:", area)


# 9. Calculate Simple Interest

principal = 10000
rate = 5
time = 2

simple_interest = (principal * rate * time) / 100

print("Simple Interest:", simple_interest)


# 10. Calculate Total and Average Marks

python = 87
java = 76
ai = 98

total = python + java + ai
average = total / 3

print("Python:", python)
print("Java:", java)
print("AI:", ai)
print("Total:", total)
print("Average:", average)


# 11. Calculate Profit

cost_price = 500
selling_price = 650

profit = selling_price - cost_price

print("Cost Price:", cost_price)
print("Selling Price:", selling_price)
print("Profit:", profit)


# 12. Calculate Discount

price = 1000
discount = 10

discount_amount = price * discount / 100
final_price = price - discount_amount

print("Price:", price)
print("Discount:", discount)
print("Discount Amount:", discount_amount)
print("Final Price:", final_price)


# 13. Calculate Age

birth_year = 2005
current_year = 2026

age = current_year - birth_year

print("Birth Year:", birth_year)
print("Current Year:", current_year)
print("Age:", age)