# -*- coding: utf-8 -*-
"""keyword.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pQGEkj0FdXmi66sbm6ff7F5xu72TQY75
"""

# This program is used to demonstrate Python keywords

import keyword

# Display all Python keywords
print("Python Keywords:")
print(keyword.kwlist)

# Display the total number of keywords
print("Total number of keywords:", len(keyword.kwlist))

# Check whether "hi" is a keyword
print("Is 'hi' a keyword?", keyword.iskeyword("hi"))

# Check whether "import" is a keyword
print("Is 'import' a keyword?", keyword.iskeyword("import"))