# -*- coding: utf-8 -*-
"""Conditional_Statements.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c4Sr3dNCl9EWjMdlDo3CEzmwx5sNLlpF
"""

# PYTHON BASIC PRACTICE PROGRAMS
# Topics Covered:
# 1. Conditional Statements
# 2. Comparison & Logical Operators
# 3. For Loop
# 4. Range Function
# 5. Loop Control Statements



# 1. POSITIVE OR NEGATIVE NUMBER


num = 10

if num > 0:
    print("Positive")
else:
    print("Negative")



# 2. EVEN OR ODD NUMBER


num = 15

if num % 2 == 0:
    print("Even")
else:
    print("Odd")



# 3. VOTING ELIGIBILITY


age = 22

if age >= 18:
    print("Eligible to vote")
else:
    print("Not eligible to vote")



# 4. LARGEST OF TWO NUMBERS

num1 = 30
num2 = 10

if num1 > num2:
    print(num1)
else:
    print(num2)



# 5. PASS OR FAIL


marks = 65

if marks >= 40:
    print("Pass")
else:
    print("Fail")



# 6. POSITIVE, NEGATIVE OR ZERO


num = 0

if num > 0:
    print("Positive")
elif num < 0:
    print("Negative")
else:
    print("Zero")



# 7. LARGEST OF THREE NUMBERS


num1 = 10
num2 = 25
num3 = 15

if num1 > num2 and num1 > num3:
    print(num1)
elif num2 > num1 and num2 > num3:
    print(num2)
else:
    print(num3)



# 8. PRINT NUMBERS FROM 1 TO 5


for i in range(1, 6):
    print(i)



# 9. PRINT NUMBERS FROM 1 TO 10


for i in range(1, 11):
    print(i)



# 10. PRINT EVEN NUMBERS FROM 1 TO 10

for i in range(1, 11):
    if i % 2 == 0:
        print(i)



# 11. PRINT ODD NUMBERS FROM 1 TO 10


for i in range(1, 11):
    if i % 2 == 1:
        print(i)



# 12. SUM OF NUMBERS FROM 1 TO 10


total = 0

for i in range(1, 11):
    total = total + i

print(total)



# 13. MULTIPLICATION TABLE OF 5


for i in range(1, 11):
    print(5 * i)



# 14. CHECK DIVISIBILITY BY 5


num = 10

if num % 5 == 0:
    print("Divisible by 5")
else:
    print("Not divisible by 5")



# 15. CHECK WHETHER TWO NUMBERS ARE EQUAL OR NOT


num1 = 10
num2 = 20

if num1 != num2:
    print("Not Equal")
else:
    print("Equal")



# 16. CHECK POSITIVE ODD NUMBER


num = 1

if num > 0 and num % 2 == 1:
    print("Positive Odd")
else:
    print("Not Positive Odd")



# 17. CHECK POSITIVE EVEN NUMBER


num = 2

if num > 0 and num % 2 == 0:
    print("Positive Even")
else:
    print("Not Positive Even")



# 18. STUDENT GRADE CLASSIFICATION


marks = int(input("Enter your marks: "))

if marks >= 75:
    print("Distinction")
elif marks >= 60:
    print("First Class")
elif marks >= 50:
    print("Second Class")
elif marks >= 40:
    print("Pass")
else:
    print("Fail")



# 19. SMALLEST OF THREE NUMBERS


num1 = 10
num2 = 5
num3 = 15

if num1 < num2 and num1 < num3:
    print(num1)
elif num2 < num1 and num2 < num3:
    print(num2)
else:
    print(num3)



# 20. AGE CATEGORY


age = 15

if age < 13:
    print("Child")
elif age < 20:
    print("Teenager")
else:
    print("Adult")



# 21. POSITIVE EVEN, POSITIVE ODD, NEGATIVE OR ZERO


num = 8

if num > 0 and num % 2 == 0:
    print("Positive Even")
elif num > 0 and num % 2 == 1:
    print("Positive Odd")
elif num < 0:
    print("Negative")
else:
    print("Zero")



# 22. BREAK STATEMENT


for i in range(1, 11):
    if i == 5:
        break
    print(i)



# 23. CONTINUE STATEMENT


for i in range(1, 11):
    if i == 3:
        continue
    print(i)
```