# -*- coding: utf-8 -*-
"""Data_type.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15VRrgEhnISvFNf1i53vJalFvL7Lp1HTP
"""

# Python Data Types - Examples and Type Conversion


# String, Integer, Float, Boolean
name = "Akshata"
age = 22
marks = 89.7
course = "python"
city = "jath"
is_student = True

print(type(name))
print(type(age))
print(type(marks))
print(type(course))
print(type(city))
print(type(is_student))


# Integer Data Type
print(type(10))
print(type(25))
print(type(100))
print(type(500))


# Float Data Type
print(type(10.0))
print(type(20.0))
print(type(32.2))
print(type(22.1))


# Boolean Data Type
print(type(True))
print(type(False))


# List Data Type
print(type([10, 20, 30]))
print(type(["Python", "Java", "C++"]))
print(type([1, "Akshata", 22.5, True]))


# Tuple Data Type
subjects = ("Python", "Java", "C++", "HTML")

print(type(subjects))


# Dictionary Data Type
students = {
    "Name": "Akshata",
    "Age": 22,
    "Course": "python",
    "City": "jath"
}

print(students)
print(type(students))


# Set Data Type
courses = {"python", "java", "php", "ai"}

print(type(courses))


# Integer Type Conversion
age = int(input("Enter your age:"))

print(type(age))


# Float Type Conversion
marks = float(input("Enter your marks:"))

print(type(marks))


# String Type Conversion
name = str(input("Enter your name:"))

print(type(name))


# Data Type and Memory Size
import sys

a = 10
name = "akshata"
phno = 987654
price = 876.90

print(type(a), sys.getsizeof(a))
print(type(name), sys.getsizeof(name))
print(type(phno), sys.getsizeof(phno))
print(type(price), sys.getsizeof(price))