# -*- coding: utf-8 -*-
"""Function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gUQbHFWzaiemEfVQWvJA4RE-eKEDQ_W9
"""

# 1. Addition of Two Numbers


def add_numbers(a, b):
    return a + b

result = add_numbers(10, 20)
print(result)



# 2. Multiplication of Two Numbers


def multiply_numbers(a, b):
    return a * b

result = multiply_numbers(5, 4)
print(result)



# 3. Division of Two Numbers


def divide_numbers(a, b):
    return a / b

result = divide_numbers(20, 5)
print(result)



# 4. Function with Default Argument


def greet(name="Akshata"):
    return "Hello " + name

print(greet())
print(greet("Priya"))



# 5. Function with *args


def add_numbers(*numbers):
    return sum(numbers)

result = add_numbers(5, 10, 15, 20)
print(result)



# 6. Function with **kwargs


def student_info(**details):
    return details

result = student_info(
    name="Akshata",
    age=22,
    course="Python"
)

print(result)



# 7. Subtraction of Two Numbers


def subtract_numbers(a, b):
    return a - b

result = subtract_numbers(23, 4)
print(result)



# 8. Check Even or Odd


def check_even_odd(number):
    if number % 2 == 0:
        return "Even"
    else:
        return "Odd"

result = check_even_odd(10)
print(result)


# 9. Check Even or Odd - Another Example


def check_even_odd(number):
    if number % 2 == 0:
        return "Even"
    else:
        return "Odd"

result = check_even_odd(11)
print(result)



# 10. Find Largest of Two Numbers


def find_largest(a, b):
    if a > b:
        return a
    else:
        return b

result = find_largest(25, 40)
print(result)



# 11. Find Largest of Three Numbers


def find_largest(a, b, c):
    if a > b and a > c:
        return a
    elif b > a and b > c:
        return b
    else:
        return c

result = find_largest(25, 40, 30)
print(result)



# 12. Calculate Square of a Number


def square(number):
    return number * number

result = square(5)
print(result)



# 13. Calculate Total Marks


def calculate_total(marks):
    return sum(marks)

result = calculate_total([70, 45, 30, 20])
print(result)



# 14. Calculate Average Marks


def calculate_average(marks):
    return sum(marks) / len(marks)

result = calculate_average([70, 80, 60])
print(result)



# 15. Student Pass or Fail


def student_result(marks):
    average = sum(marks) / len(marks)

    if average >= 40:
        return "Pass"
    else:
        return "Fail"

result = student_result([70, 45, 30, 20])
print(result)



# 16. Student Information using Dictionary

def student_info(name, age, course):
    student = {
        "name": name,
        "age": age,
        "course": course
    }

    return student

result = student_info("Akshata", 22, "Python")
print(result)