# -*- coding: utf-8 -*-
"""Operators.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LsWm_OVOYOZm8pUwrHOtSIgRVM8nporb
"""

# 1. Arithmetic Operators

a = 10
b = 20
print("Addition:", a)

a = 40
b = 20
print("Subtraction:", a - b)

a = 34
b = 21
print("Multiplication:", a * b)

a = 20
b = 34
print("Division:", a / b)

a = 24
b = 6
print("Remainder:", a % b)

a = 34
b = 3
print("Floor division:", a // b)

a = 3
b = 4
print("Power:", a ** b)



# 2. Comparison Operators


a = 10
b = 20

print(a == b)
print(a != b)
print(a > b)
print(a < b)
print(a >= b)
print(a <= b)


a = 45
b = 30
print(a > b)

a = 25
b = 25
print(a == b)



# 3. Logical Operators


a = 10
b = 20
print(a > 10 and b < 20)

a = 15
b = 10
print(a > 10 and b < 20)


a = 15
b = 30
print(a > 20 or b > 20)

a = 10
print(not a > 5)



# 4. Assignment Operators

balance = 1000
deposit_amount = 500

balance += deposit_amount
print("Final balance:", balance)

withdraw_amount = 200

balance -= withdraw_amount
print("Final balance:", balance)



# 5. Membership Operators

students = ["Ashok", "Ramesh", "Suresh"]

print("Ashok" in students)
print("John" in students)
print("Kiran" not in students)



# 6. Identity Operators


a = 10
b = 10

print(a is b)
print(a is not b)