# -*- coding: utf-8 -*-
"""python_variables.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DBUqnPdLvJb4-ufGnE44GHlM-bUEc2HH
"""

#### Python Variables

######Student Information#####

name="Akshata"
age=22
city="jath"
course="python"
marks=87
print("name:",name)
print("age:",age)
print("city:",city)
print("course:",course)
print("marks:",marks)


######Student Marks###

Python=85
Database=78
Java=82
total=Python+Database+Java
Average=total/3
print("Python:",Python)
print("Database:",Database)
print("Java:",Java)
print("Total marks:",total)
print("Average:",Average)


######addition two numbers##
a=20
b=10
print("Addition:",a+b)

###data type
name="Akshat"
age=22
marks=78
is_student=True
print(type(name))
print(type(age))
print(type(marks))
print(type(is_student))


########## Taking Integer Input
name=input("Enter your name:")
age=int(input("Enter your age:"))
marks=int(input("Enter your marks:"))
print("name:",name)
print("age:",age)
print("marks:",marks)



##### use input()

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
